version: '3'

services:
  nginx:
    image: openpanel/opennginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /etc/openpanel/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/openpanel/nginx/vhosts/default.conf:/etc/nginx/sites-available/default
        - /etc/openpanel/nginx/vhosts/default.conf:/etc/nginx/sites-enabled/default
        - /etc/openpanel/nginx/vhosts/openpanel_proxy.conf:/etc/openpanel/nginx/vhosts/openpanel_proxy.conf
        - /etc/nginx/sites-available/:/etc/nginx/sites-available/
        - /etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
        - /etc/openpanel/nginx/error_pages/snippets/:/etc/nginx/snippets/
        - /etc/openpanel/nginx/error_pages/:/srv/http/default/
        - /var/log/nginx/stats/:/var/log/nginx/stats/
        - /var/log/nginx/domlogs/:/var/log/nginx/domlogs/
        - /etc/letsencrypt/:/etc/letsencrypt/
        - /etc/openpanel/openpanel/core/users/:/etc/openpanel/openpanel/core/users/
    depends_on:
      - certbot
    network_mode: host

  modsecurity:
    image: owasp/modsecurity-crs:nginx
    volumes:
      - /etc/openpanel/nginx/modsecurity:/etc/nginx/modsecurity

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt
      - /etc/openpanel/nginx:/etc/nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
